### ISSUE TITLE
Not yours

### ISSUE THREAD

**Issue by Matthww** [PMDE-Dev/MCMMO#1]
This plugin is not yours

It's made by Angelo Vidrio

stop copying plugins

**Comment by ExaSonit** [comment]
what's the utility of this plugin??

**Comment by LordJoshie** [comment]
Talk about not his.... 

I discovered this plugin by doin a search based on this 


https://sellfy.com/p/TWPw/


so who really owns the plugin?

**Comment by ExaSonit** [comment]
We forked another repository

**Comment by caspervanneck** [comment]
@ExaSonit sluit het gewoon het is spam

**Comment by Matthww** [comment]
The plugin you mentioned in the selffy is made from scratch you just copied all the files from a old mcmmo plugin and changed all the author names

**Comment by ExaSonit** [comment]
It's just spam -_-
